import React, { useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity, Image, BackHandler, StatusBar, useColorScheme, useWindowDimensions } from 'react-native';
import ScreenScroll from './components/ScreenScroll';
import { Colors } from 'react-native/Libraries/NewAppScreen';

const TermsofService = ({ navigation, route }) => {
  const isDarkMode = useColorScheme() === 'dark';
  const { width, height } = useWindowDimensions();
  const isLandscape = width > height;
  const landscapeSection = { width: '100%', marginHorizontal: 0, paddingHorizontal: 8 };
  const infoBoxLandscape = { width: '100%', maxWidth: undefined, marginHorizontal: 0, paddingHorizontal: 12 };
  // Apply runtime overrides so all section containers and infoBoxes become full-width in landscape
  if (isLandscape) {
    try {
      if (styles && styles.sectionContainer) {
        Object.assign(styles.sectionContainer, { width: '100%', marginHorizontal: 0, paddingHorizontal: 8, alignSelf: 'stretch' });
      }
      if (styles && styles.infoBox) {
        Object.assign(styles.infoBox, { width: '100%', maxWidth: undefined, marginHorizontal: 0, paddingHorizontal: 12, alignSelf: 'stretch' });
      }
    } catch (e) {
      // ignore
    }
  }
  const backgroundStyle = {
    backgroundColor: isDarkMode ? '#2a3144' : Colors.white,
  };

  useEffect(() => {
    const backAction = () => {
      if (navigation && typeof navigation.canGoBack === 'function' && navigation.canGoBack()) {
        navigation.navigate('My Profile');
        return true;
      }
      if (route && route.params && route.params.origin) {
        navigation.navigate(route.params.origin);
        return true;
      }
      return false;
    };

    const backHandler = BackHandler.addEventListener(
      'hardwareBackPress',
      backAction
    );

    return () => {
      backHandler.remove();
      StatusBar.setHidden(false);
    };
  }, [navigation]);

  return (
    <>
      <View style={[styles.container, backgroundStyle]}>
        <ScreenScroll contentContainerStyle={{ flexGrow: 1 }}>
          <View style={[
            styles.sectionContainer,
            isLandscape ? landscapeSection : null,
            { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
            { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
          ]}>
            <Text style={[
              styles.pageTitle,
              { color: isDarkMode ? '#fff' : '#1434a4' }
            ]}>
              Terms of Use</Text>
            <View style={[
              styles.sectionContainer,
              isLandscape ? landscapeSection : null,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>

              <Text style={styles.leadText}>
                This document is an electronic record in terms of the Information Technology Act,
                2000 and the rules framed thereunder. This electronic record is generated by a
                computer system and does not require any physical or digital signatures.
              </Text>
              <Text style={styles.leadText}>
                This document is published
                in accordance with the provisions of Rule 3 (1) of
                the Information Technology (Intermediaries Guidelines)
                Rules, 2011 that require publishing the rules and regulations,
                privacy policy and Terms of Use for access or usage of the https://www.allrounderbaby.com website.</Text>
              <Text style={styles.leadText}>
                Allrounder Baby is an online tool providing content such as articles, audio, video, photographs etc. for accelerated development of baby's abilities including things such as articles, audio, video, photographs, and other materials that optimize a child's developmental milestones across multiple domains, including but not limited to: Mathematical Analytical Reasoning, Verbal Communicative Fluency, Visual Perception, Kinesthetic Coordination and Control, Rhythmic and Harmonic Sensitivity and Expression, Social Interaction and Understanding, Self-awareness and Reflection, Environmental Observation and Appreciation, Philosophical Contemplation and Inquiry, Emotional Awareness and Regulation, Practical Problem-solving and Application, Innovative Imagination and Creation and is owned and operated by Sarvashine Allrounder Baby Solutions Private Limited, a company incorporated under the Companies Act, 2013, and having registered office at Flat A 304 Royal City, Potiya Road, Durg - 491001, Chattisgarh, India (hereinafter referred to as “We”, “Us”, “ Allrounder Baby”, Sarvashine” or “Our” which expression shall mean and include its affiliates, successors and permitted assigns). Your (“You” or “Your” or "User") use of the Platform (defined below) is subject to the notices, terms and conditions set forth in these Terms of Use. The domain name “https://www.allrounderybaby.com”, “https://allrounderbaby.in”, (hereinafter collectively referred to as the "Website") and mobile application “allrounder Baby” ("Allrounder baby App") is owned by Sarvashine Allrounder Baby Solutions Private Limited. The Website and Allrounder Baby App is hereinafter collectively referred to as the "Platform". Your use of the Platform is governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. You acknowledge and agree that You shall be subject to the policies that are applicable to the Platform and by mere use of the Platform, You shall be contracting with Allrounder Baby and these terms and conditions, including the policies, constitute Your binding obligations with Allrounder Baby.
              </Text>
              <Text style={styles.leadText}>
                By mere use of the Platform, You agree to be subject to the applicable rules, guidelines, policies, terms, and conditions and the same shall be deemed to be incorporated into this Terms of Use and be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. We will notify You of any material updates / changes from time to time. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.
              </Text>
              <View style={[styles.containerss, isLandscape ? { marginHorizontal: 16, paddingHorizontal: 12 } : null]}>
                <Text style={[
                  styles.platformtext,
                  { color: isDarkMode ? '#000' : '#00796B' }
                ]}>
                  ⚠️ Important: Please Read Carefully
                </Text>
                <Text style={[
                  styles.bodyText,
                  { fontSize: 14, }
                ]}>
                  ACCESSING, BROWSE OR OTHERWISE USING THE PLATFORM INDICATES YOUR ACCEPTANCE OF ALL THE TERMS AND CONDITIONS IN THESE TERMS OF USE. PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE PROCEEDING. YOU DECLARE YOUR WILLINGNESS TO ABIDE AND BE BOUND BY THESE TERMS OF USE THROUGH YOUR USE OF THE PLATFORM. IF YOU DO NOT AGREE WITH THE TERMS OF USE, PLEASE DO NOT USE THIS PLATFORM.
                </Text>
                <Text style={styles.bodyText}>
                  These Terms of Use will be effective immediately upon Your acceptance of Our terms and conditions, Your use of Our Platform being indicative of such acceptance. These Terms of Use shall be enforceable against You in the same manner as any other written agreement.
                </Text>
              </View>
            </View>
            <View style={[
              styles.sectionContainer,
              isLandscape ? landscapeSection : null,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>1. What we do</Text>
              <Text style={styles.leadText}>
                We provide Users of the Platform that provides access to certain content and services, which may include, without limitation:
              </Text>
            </View>
            <View style={[styles.infoBox, isLandscape ? infoBoxLandscape : null]}>
              <Text style={styles.bulletPoint}>
                <Text style={styles.bulletText}>
                  1.  activities and exercises that are solely focused on unlocking a baby's abilities including things like athleticism, math, reading, knowledge, memory, language development, logic, creativity, music, drama, personality, and character development.; and
                </Text>
              </Text>
              <Text style={styles.bulletPoint}>
                <Text style={styles.bulletText}>
                  2. content such as articles, audio and video clips, photographs, graphics, images, text, data, user comments, postings and messages and other similar content (such content and services, collectively, the Services).
                </Text>
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              isLandscape ? landscapeSection : null,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>2. Registration</Text>
              <Text style={styles.leadText}>
                You can access the Platform without registering for an account. However, to use several features, You will need to register and create a profile with accurate and complete information. Your profile must be your own or of a person. You are entitled to represent and You shall not use or provide any information that is offensive or that violates any third party’s rights.
              </Text>
              <Text style={styles.leadText}>
                In order to use certain aspects of the Service, You will have to register for the Service and create an account (User Account). When creating Your account for the Service, You agree to provide true, accurate, current, and complete information. You further agree to maintain and update Your personal information as needed to keep it true, accurate, current, and complete. You are solely responsible for maintaining the confidentiality of Your account and password and for restricting access to Your computer, and You agree to accept responsibility for all activities that occur under Your account or password. If You have reason to believe that Your account is no longer secure (for example, in the event of a loss, theft or unauthorized disclosure or use of Your ID, password, or any credit, debit or charge card number), You agree to immediately notify Us. You may be liable for the losses incurred by Us or others due to any unauthorized use of Your User Account.
              </Text>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>Account de-activation: </Text>
              <Text style={styles.leadText}>
                You can choose to de-activate Your account on the Platform by notifying support@allrounderbaby.com. Please note that any cancellation / deactivation of Your account shall be subject to the payment terms applicable to You.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>3. User Data</Text>

              <Text style={styles.leadText}>
                The Platform allows You to submit and access certain personal data (including but not limited to name, email address, contact number, gender, date of birth, videos , audios and photographs) (collectively, User Data).
              </Text>
              <Text style={styles.leadText}>
                By submitting User Data to Us, You hereby grant, and represent and warrant that You have all rights necessary to grant, all rights and licenses to the User Data required for Allrounder Baby and its subcontractors and service providers to provide the Services, including without limitation, features of the Services that enable You to share certain User Data with third parties through our Service. You agree that Allrounder Baby will have the right, both during and after the term of these Terms of Use, to use, store, transmit, distribute, modify, copy, display, sublicense, and create derivative works of User Data. By signing up with us, you consent to receive updates related to your account and program (such as, sign up confirmation, updated terms of service, account expiry, program details, webinar details etc) on WhatsApp.
              </Text>
              <View style={[styles.infoBox, isLandscape ? infoBoxLandscape : null]}>
                <Text style={[
                  styles.platformtext,
                  { color: isDarkMode ? '#000' : '#00796B' }
                ]}>
                  In connection with User Data, You hereby represent, warrant, and agree that:</Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    1. You have obtained the User Data lawfully, and the User Data does not and will not violate any applicable laws or any person or entity’s proprietary or intellectual property rights;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    2. the User Data is free of all viruses, Trojan horses, and other elements that could interrupt or harm the systems or software used by Allrounder Baby or its subcontractors to provide the Service;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    3. all User Data has and will be collected by You in accordance with a privacy policy that permits Allrounder Baby to share, collect, use, and disclose such User Data as contemplated under these Terms of Use (including without limitation, by enabling You to share certain User Data with third parties through the Platform), and if required by applicable law, pursuant to consents obtained by You to do each of the foregoing;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    4. You are solely responsible for ensuring compliance with all privacy laws in all jurisdictions that may apply to User Data provided hereunder;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    5. Allrounder Baby may exercise the rights in User Data granted hereunder without liability or cost to any third party; and
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    6. the User Data complies with the terms of these Terms of Use. For purposes of clarity, Allrounder Baby takes no responsibility and assumes no liability for any User Data, and You will be solely responsible for its User Data and the consequences of sharing it hereunder.
                  </Text>
                </Text>
              </View>
              <Text style={styles.leadText}>
                Information about Your hardware and software may be automatically collected by Us. This information can include usage information that includes Your interactions with Services, device information, such as unique device identifiers, operating system information, internet service provider, IP address, screen resolution, language, the date and time of each of Your log-ins and requests. This information is used for the operation of Services, to maintain quality of the Service, and to provide general statistics regarding use of Services. This information we otherwise receive.
              </Text>
              <Text style={styles.leadText}>
                In the event that User Data is disclosed to or accessed by an unauthorized party, Allrounder Baby will promptly notify You and use reasonable efforts to cooperate with Your investigation of the incident.   Allrounder Baby will not be responsible for any backup, recovery or other steps required to ensure that User Data is recoverable in the case of data loss. You are solely responsible for backing up Your User Data on a regular basis, and taking appropriate steps to safeguard and ensure the integrity of Your User Data.
              </Text>
              <Text style={styles.leadText}>
                You own all right, title and interest (including all intellectual property rights) in and to Your User Data. Following Your use of the Services,
                You may submit a written request to the Company to remove from the Company’s systems any User Data consisting of personally identifiable information
                and following the receipt of such request, Company shall promptly delete any such personally identifiable information from its systems. Company shall
                provide to You a copy of Your User Data promptly following Your written request for such User Data.
              </Text>
              <Text style={styles.leadText}>
                You shall not host, display, upload, modify, publish, transmit, update or share any information that:
              </Text>
              <View style={styles.appText}>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    1. belongs to another person and to which You do not have any right;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    2. is grossly harmful, harassing, libelous, invasive of another’s privacy, hateful or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, otherwise unlawful in any manner whatsoever;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    3. harms minors in any way;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    4. infringes any patent trademark, copyright or other proprietary rights;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    5. violates any law for the time being in force;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    6. deceives or misleads the Users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    7. impersonates another person; or
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    8. threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with friendly states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation. You understand that any content You find on or through the Platform is the sole responsibility of the person who originated such content. You confirm that You are not relying on Allrounder Baby to, and that You understand that We do not, endorse, support, represent or guarantee the completeness, truthfulness, accuracy or reliability of any content or communications posted via the Platform or endorse any opinions expressed on the Platform. You understand that Your content may be republished and if You do not have the right to submit content for such use, it may subject You to liability, and that Allrounder Baby will not be responsible or liable for any use of Your content by Allrounder Baby in accordance with these Terms of Use.
                  </Text>
                </View>
              </View>
              <Text style={[
                styles.leadText,
                {
                  marginTop: 20,

                }
              ]}>
                As part of the Services, We may collect certain personal information (including but not limited to phone number and email address),
                and let You interact with other users of the Platform via 'WhatsApp' or other social media or other third party service platform.
                Details of the types of information We collect and the end use for such information is provided in Our privacy policy which can be
                accessed https://www.allrounderbaby.com/privacy-policy. You acknowledge that We do not control what users do with the information
                they obtain from 'WhatsApp' or other social media or other third party service platform. You acknowledge that We are not responsible
                or liable for interactions involved between users/third parties. We are not liable for disputes, claims, losses, injuries or damage of
                any kind that arise out of or relate to the conduct of users of the Platform and/or any third party.
              </Text>
              <Text style={styles.leadText}>
                Just as other Users may have access to Your personal information, You too may have access to their personal information. You agree that You shall only use the personal information in relation to the use of the Services and shall not misuse such personal information for any unsolicited communication, marketing or spam. Your breach of these terms will be viewed seriously and may result in an immediate suspension or termination of Your account and Your access to the Services.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              isLandscape ? landscapeSection : null,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>4. Payment</Text>
              <Text style={styles.leadText}>
                Certain features and services available on the Platform are accessible only upon payment (Services). The consideration for the Services and any other charges due from You shall be as per the rates in effect at the time at which it is charged. The Services may differ geographically and the plans and pricing may also vary with time and place. We reserve the right to introduce or remove plans and pricing from time to time. When You purchase a Service, You must provide Us with complete and accurate payment information thereby authorizing Us to charge You for the Service availed. In the event of failure to remit the payment, access to the Service shall not be commenced or shall stand terminated. You acknowledge that You will be able to access content of the course on the Platform only upon making full payment for such course. You agree and acknowledge that prices may vary for different courses.
              </Text>
              <Text style={styles.leadText}>
                Information submitted or collected on the Platform or pursuant to the use of the Services is stored in a database. Specifically, We store the username, name, e-mail address, contact number, for continued and uninterrupted services. We use the services of third party payment service providers to process Your payment and share the payment information and other identifiers with such third parties in accordance with their terms and conditions. Accordingly, Your payments to Us through such third party services shall be in accordance with the terms and conditions of adopted and implemented by such service provider, and we shall not be responsible for any failed or incomplete fulfilment of any payment instructions issued by You through such service provider or any actions taken by You in respect of the same. At the time of payment, Your bank or other third party payment intermediaries may charge You currency conversion fees, bank charges and other transaction fees which shall be payable by You.
              </Text>
              <Text style={styles.leadText}>
                You may view Your past payments and invoices, if any, on the Platform. Invoices for payments will also be delivered to the e-mail address registered with Us upon successful payment.
              </Text>
              <Text style={styles.leadText}>
                The payments made to Us shall be inclusive of all taxes payable by Us including Goods and Services Tax payable in India, if any. All invoices are payable in Indian Rupees or any other currencies that we may bill You based on the country You are located in. If there are any withholding taxes in respect of payments made to Us applicable to Your jurisdiction, the billing shall be deemed to have been grossed up by an amounts such that after deduction of such applicable taxes, We receive the same amount from You as We would have received had there been no such withholding or deduction.
              </Text>
              <Text style={styles.leadText}>
                Allrounder Baby accepts INR, USD, and EUR for payments. Foreign currency payments are subject to real-time exchange rates and conversion fees imposed by banks/payment gateways.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>5. Refunds</Text>
              <Text style={styles.leadText}>
                Access to the Services commences immediately on the realization of payment of the fees. You agree that You can request a refund of fees from Us only if You request refund as per refund policies as provided on the Platform. Refund policies may vary by region due to currency exchange and transaction costs.It is clarified that there shall be no refund for subscriptions to any subsequent course. The refund will be credited through the payment method You used to make payment. In any other case, all payments are non-refundable.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>6.  Representations and Warranties</Text>
              <View style={styles.appText}>
                <Text style={[
                  styles.platformtext,
                  {
                    color: isDarkMode ? '#000' : '#00796B',
                    marginLeft: 18,
                    marginBottom: -10,
                  }
                ]}>
                  You hereby represent and warrant:</Text>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    1. That You have the right, authority, and capacity to enter into this Terms of Use on Your own behalf and on behalf on any person for whom You are acting and to abide by all of the terms and conditions contained herein, and that if any aspect of Your participation violates provisions of the law to which You are subject, You will cease using the services and close your account;          </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    2. That You are at least 18 (eighteen) years old and competent to execute and perform into any agreement You enter into through Our Platform;          </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    3. That You shall not use a false name or email address owned or controlled by another person with the intent to impersonate that person or for any other reason;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    4. That You shall not use a user ID name that is subject to any rights of a person other than yourself without appropriate authorization;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    5. violates any law for the time being in force;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    6.That You shall be solely responsible for maintaining the confidentiality of Your password;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    7.  That all the representations made by You to Us including in accordance with these terms and conditions are true, correct
                    and complete and that You will update Your registration information with the Company as needed so that it remains true, correct and complete; and
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    8. That You will conduct yourself in a professional manner in all Your interactions with any other user.          </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    9.That Your usage of the Platform will not, in any manner, directly or indirectly, violate terms of any contractual arrangement binding on You.
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    10. You are capable of assessing surroundings and identifying risks involved with each exercise in the Services and are responsible and shall solely be liable for the consequences of any injury to Your child and Yourself.
                  </Text>
                </View>
              </View>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                {
                  color: isDarkMode ? '#fff' : '#1434a4',
                  marginTop: 20,
                }
              ]}>7. Emails, Newsletters and Notifications</Text>
              <Text style={styles.leadText}>
                If You wish to subscribe to Our newsletter(s) or receive notifications or e-mails from Us, We will use Your name, contact number and latest e-mail address provided by You in this regard. However, You may choose to stop receiving Our newsletters by following the instructions to unsubscribe as included in these e-mails or You can contact Us at support@allrounderbaby.com
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>8. Intellectual Property</Text>
              <Text style={styles.leadText}>
                This Platform is operated by and is the sole property of Allrounder Baby. Any and all material on this Platform, including images, illustrations, audio and video clips, trade names, proprietary information and knowledge, technology, databases, or rights with respect thereto necessary for Our business as is now being operated are protected by copyrights, trademarks, and other intellectual property rights that are owned by Us or by other parties that have licensed such material to Us, or such parties having ownership of content uploaded on the Platform. You agree that any and all material displayed on the Platform is solely for Your personal use and You shall not, whether directly or indirectly, copy, reproduce, republish, post, upload, transmit or distribute such material in any manner and through any media including by way of e-mail or other electronic means and You shall not assist any other person in doing so. Modification of the said materials or use of the materials on any other Platform or networked computer environment or use of the materials for any purpose other than personal use is a violation of the said copyrights, trademarks and other intellectual proprietary rights, and is expressly prohibited. Allrounder Baby grants to You a temporary, non-exclusive, revocable, non-transferable limited license to use the Platform for Your own use. All right, title, and interest in and to the Platform (excluding content uploaded specifically by a user) is and will remain the exclusive property of Allrounder Baby and/or its licensors.
              </Text>
              <Text style={styles.leadText}>
                You agree that these Terms of Use do not entitle You to any support, additional materials or courses, upgrades, updates, add-ons, patches, enhancements, or fixes for the Platform (Updates). We may, however, occasionally provide automatic Updates to the Platform at its sole discretion (and without any advanced notification to You). Any such Updates shall become part of the services and subject to these Terms of Use.
              </Text>
              <Text style={styles.leadText}>
                From time to time, We test various aspects of Our Platform, including Our Website, user interfaces, service levels, plans, promotions, features, availability of content, delivery, and pricing, and we reserve the right to include You in or exclude You from these tests without notice.
              </Text>
              <Text style={styles.leadText}>
                By submitting any content or material to the Platform including names, logos, photos videos and/or any material, whether protected through trademark, copyright, word mark, etc. or not, including those of Yourself, Your child or Your family members, You hereby grants Allrounder Baby a worldwide, non-exclusive, royalty-free, perpetual, sub-licensable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the such content in connection with the Platform and Allrounder Baby’s business, including without limitation for promoting and redistributing part or all of the Platform (and derivative works thereof) in any media formats and through any media channels. In the event it does so, Allrounder Baby will seek to maintain the confidentiality of the content consistent with Your account classification, but once again cannot guarantee any such confidentiality. Upon Your request, We will use Our commercial best efforts to remove all the content or material submitted by You on the Platform.
              </Text>
              <Text style={styles.leadText}>
                Allrounder Baby shall have no obligation to monitor or enforce any intellectual property rights that may be associated with the content provided by You on the Platform. We secure Your personal information from loss, misuse, unauthorized access, disclosure, alteration, and destruction. Although We take reasonable measures to do so, please remember that no transmission of data over the internet or any wireless network can be guaranteed to be 100% secure. As a result, We cannot ensure or warrant the security of any information that You transmit to Us or from Us, and You do so at Your own risk.
              </Text>
              <Text style={styles.leadText}>
                If You are a copyright owner or an agent thereof and believe that any content on the Platform infringes upon Your rights, or if You wish to remove any material submitted by You from our promotional packages, You may contact support@allrounderbaby.com and provide details requested in regard to such infringement. While we will remove the inform such materials as soon as commercially feasible from our Platform, it may not be possible to remove marketing or other materials that have been sent to third parties and which are no longer in our control.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>9. Prohibited Uses</Text>
              <View style={styles.purposes}>
                <Text style={[
                  styles.platformtext,
                  {
                    color: isDarkMode ? '#000' : '#00796B',
                    marginLeft: 18
                  }
                ]}>
                  The Platform may be used only for lawful purposes. Allrounder Baby specifically prohibits any use of the Platform for
                  and You agree not to use the Platform for any of the following purposes:
                </Text>
                <View style={styles.listContainer}>
                  <Text style={styles.leadText}>
                    1.Modifying, publishing, storing, transmitting, distributing, displaying, performing, participating in the transfer or sale of, create derivative works on, or in any way exploiting, any of the copyrighted material contained on the Platform, in whole or in part, without Our prior written consent; or                </Text>
                  <Text style={styles.leadText}>
                    2.Subleasing, leasing, selling, assigning, transferring, distributing, renting, permitting concurrent use of, or granting other rights in the content and any material and documentation provided on the Platform by other Users or Allrounder Baby to any third party;                </Text>
                  <Text style={styles.leadText}>
                    3.Providing use of the content in a computer service business, network, time sharing, interactive cable television, multiple CPU or multiple or concurrent user arrangement to Users who are not individually licensed by Allrounder Baby or otherwise exploiting any portion of, the use of or access to the content or the materials or documentation provided on the Platform in contravention of these Terms of Use;                </Text>
                  <Text style={styles.leadText}>
                    4.defame, libel, disparage, threaten, harass or intimidate anyone or otherwise violate the personal, privacy, contractual, intellectual property or other rights of any person, including by the use of offensive comments related to race, national origin, gender, sexual preference or physical handicap;                </Text>
                  <Text style={styles.leadText}>
                    5.submit any content or material that falsely expresses or implies that such content or material is sponsored or endorsed by Allrounder Baby; or                </Text>
                  <Text style={styles.leadText}>
                    6.sell access to the Platform or any part thereof other than through a mechanism expressly approved by Allrounder Baby.                </Text>
                </View>
              </View>
              <Text style={styles.leadText}>
                Allrounder Baby may also place additional fair use restrictions including restrictions on concurrent connections and time of usage.
              </Text>

            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>10. Modifications</Text>

              <Text style={styles.leadText}>
                We reserve the right at any time and from time to time, in Our sole discretion, to modify the content on the Platform or any part thereof, including the transmission of any related materials or documentation, with or without providing prior notice to You. We further reserve the right at any time and from time to time, at Our sole discretion, to alter, modify or terminate any content or features contained on the Platform without providing to You prior notice of such alteration, modification or termination. You agree that Allrounder Baby shall not be liable to You or to any third party claiming through You, for any modification of the content or features provided on the Platform.
              </Text>
            </View>
            <View>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>11. System Limitations and Failures</Text>

              <Text style={styles.leadText}>
                We use internally developed systems for providing You access to and facilitating Your use of the Platform. These systems may encounter technical or other limitations, and computer and communications hardware systems might experience interruptions. Further, We continually enhance and improve these systems in order to accommodate the level of use of the Platform. We may also add additional features and functionality to Platform that might result in the need to develop or license additional technologies. Increased utilization of the Platform or providing new features or functionality may cause unanticipated system disruptions, slower response times, degradation in levels of customer service, and delays in reporting accurate financial information. You agree that We shall not be liable to You or to any third party claiming through You, for any such failures contemplated herein.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>12. Privacy and Confidentiality</Text>

              <Text style={styles.leadText}>
                Your use of the Platform is governed by Our privacy policy, which can be located at Please read Our privacy policy to understand Our
                information collection and usage practices. You may obtain certain confidential information, including without limitation, technical,
                contractual, product, pricing, business related functions, activities and services, customer lists, customer's contact number, knowledge
                of customer needs and preferences, business strategies, marketing strategies, methods of operation, markets and other valuable information
                that should reasonably be understood as confidential (Confidential Information). You acknowledge and agree to hold all Confidential
                Information in strict confidence. Title and all interests to all Confidential Information shall be vested in Us. Your obligations
                regarding Confidential Information will survive the termination of these Terms of Use in accordance with Paragraph 17 below. Upon
                such termination, You must stop forthwith using any Confidential Information to which You may have been exposed in due course
                of Your use of the Platform.
              </Text>
              <View style={[styles.infoBox, isLandscape ? infoBoxLandscape : null]}>
                <Text style={[
                  styles.platformtext,
                  {
                    color: isDarkMode ? '#000' : '#00796B',
                    fontSize: 16
                  }
                ]}>
                  You agree that Your obligations under this Paragraph 12 are necessary and reasonable in order to protect Our business and expressly agree that monetary damages would be inadequate to compensate for any breach of any covenant or agreement set forth herein. Accordingly, You agree and acknowledge that any such violation or threatened violation will cause irreparable harm and injury to Allrounder Baby and that, in addition to any other remedies that may be available, in law, equity or otherwise, Allrounder Baby shall be entitled to obtain injunctive relief against the threatened breach of the terms of this Paragraph 12 or the continuation of any such breach.
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    1. required by the applicable law of any jurisdiction;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    2. required by any applicable securities exchange, supervisory or regulatory or governmental body to which the relevant party is subject or submits, wherever situated, whether or not the requirement for disclosure has the force of law;  or
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    3. made to employees and representatives on a need to know basis, provided that such persons are required to treat such information as confidential through written agreement in terms which are no less strict than this Paragraph 12. Provided that, restriction in this Paragraph 12 shall not apply to disclosures of Confidential Information made by Allrounder Baby to its shareholders, directors, managers, advisors, potential investors and/or affiliates. Provided further that Allrounder Baby may disclose the Confidential Information to third party vendors and customers or pursuant to partnering arrangements without the restriction of this Paragraph 12 provided that such persons are required to treat such information as confidential through written agreement in terms which are no less strict than this Paragraph 12.
                  </Text>
                </Text>
              </View>
              <Text style={styles.leadText}>
                Provided further that Allrounder Baby may disclose the Confidential Information to third party vendors and customers or pursuant to partnering arrangements without the restriction of this Paragraph 12 provided that such persons are required to treat such information as confidential through written agreement in terms which are no less strict than this Paragraph 12.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>13. Additional / Special Terms and Conditions</Text>

              <Text style={styles.leadText}>
                Allrounder Baby may notify You or request You to accept additional or special terms and conditions in relation to Your access to certain features or services on the Platform. You agree that You shall access or use such features and services only in accordance with such additional or special terms and conditions as if they were incorporated herein these Terms of Use.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>14. Links to / from other Platforms and Third Party Tools</Text>
              <Text style={styles.leadText}>
                The Platform may contain link/s to various other websites. These links are provided solely for Your convenience and benefit. Wherever such link/s lead to websites which are not owned by or belong to Allrounder Baby, We shall not be responsible for the content, products and services provided on such linked sites. We do not warrant or make any representations regarding the correctness or accuracy of the content on such websites. If You decide to access such linked websites, You do so at Your own risk. We do not in any way endorse the linked websites.
              </Text>
              <Text style={styles.leadText}>
                Similarly, this Platform can be made accessible through a link created by other websites. Access to this Platform through such link/s shall not mean or be deemed to mean that the objectives, aims, purposes, ideas, concepts of such other websites or their aim or purpose in establishing such link/s to this Platform are necessarily the same or similar to the idea, concept, aim or purpose of Our Platform or that such links have been authorized by Us. We are not responsible for any representation/s of such other websites while affording such link and no liability can arise upon Allrounder Baby consequent to such representation, its correctness or accuracy. In the event that any link/s afforded by any other website/s derogatory in nature to the objectives, aims, purposes, ideas and concepts of this Platform, is utilized to visit this Platform and such event is brought to the notice or is within the knowledge of Allrounder Baby, civil or criminal remedies as may be appropriate shall be invoked.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>15. Security</Text>

              <View style={[styles.infoBox, isLandscape ? infoBoxLandscape : null]}>
                <Text style={[
                  styles.platformtext,
                  {
                    color: isDarkMode ? '#fff' : '#00796B',
                    marginLeft: 7
                  }
                ]}>
                  You are prohibited from violating or attempting to violate the security of the Platform, including, without limitation:</Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    1. accessing data not intended for You or logging into an account which You are not authorized to access;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    2. attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization;
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    3. interfere with service to any user, host, or network.
                  </Text>
                </Text>
              </View>
              <Text style={styles.leadText}>
                You shall not misuse this Platform by knowingly introducing viruses, Trojans, worms, logic bombs or other materials that are malicious or technologically harmful (Viruses). You must not attempt to gain unauthorized access to our Platform, the server on which the Platform is stored or any server, computer or database connected to this Platform. You must not attack this Platform via a denial-of-service attack. Further, You shall not interfere with or circumvent any security feature of the Platform or any feature that restricts or enforces limitations on use of or access to the Platform, such as probing or scanning the vulnerability of any system, network or breach.
              </Text>
              <Text style={styles.leadText}>
                By breaching the provisions of this Paragraph 15, You may be liable to be prosecuted under the Information Technology Act, 2000 and any other applicable law. We will report any such breach to the relevant law enforcement authorities and We will cooperate with such authorities by disclosing Your identity to them. In the event of such a breach, Your rights to use this Platform will cease immediately.
              </Text>
              <Text style={styles.leadText}>
                We will not be liable for any loss or damage caused by a denial-of-service attack or Viruses that may infect Your computer equipment, computer programs, data or other proprietary material due to Your use of this Platform or to Your downloading of any material posted on it, or on any Platform linked to it.
              </Text>
              <Text style={styles.leadText}>
                You agree to immediately report to Us all incidents involving suspected or actual unauthorized access, disclosure, alteration, loss, damage, or destruction of data.
              </Text>
              <Text style={styles.leadText}>
                You shall not interfere with or disrupt (or attempt to interfere with or disrupt) access and enjoyment of the Platform of other Users or any host or network, including, without limitation, creating or transmitting unwanted electronic communications such as “spam” to other Users, overloading, flooding or mail-bombing the Platform, or scripting the creation of content in such a manner as to interfere with or create an undue burden on the Platform
              </Text>
              <Text style={styles.leadText}>
                You are prohibited from reverse engineering, decompiling, reverse assembling, modifying or attempting to discover or copy any software, source code or structure that the Platform utilizes to generate web pages or any software or other products or processes accessible through the Platform.
              </Text>
              <Text style={styles.leadText}>
                All actions performed by any person using Your account and password shall be deemed to have been committed by You and You shall be liable for the same. Allrounder Baby reserves the right to suspend/terminate Your account at any time if it is found that You have been sharing the password with any unauthorized user.
              </Text>
              <Text style={styles.leadText}>
                In order to reduce the risk of unauthorized access, all accounts maintained with Us through the Platform are locked after 5 (five) consecutive incorrect login attempts. In the event of such lockout, You can email the administrator at support@allrounderbaby.com and the account shall be unlocked upon receipt of Your email. You can also request for a password reset on Our Website through the ‘forgot password’ option on Our Platform.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>16. Security</Text>

              <Text style={styles.leadText}>
                All electronic communications and content presented and/or passed to Us, including that presented and/or passed from remote access connections, may be monitored, examined, saved, read, transcribed, stored, or retransmitted in the course of daily operations by any duly authorized employee or agent of Allrounder Baby in the exercise of their duties, or by law enforcement authorities who may be assisting Allrounder Baby in investigating possible contravention / non-compliance with applicable law. Electronic communications and content may be examined by automated means. Further, Allrounder Baby has the right to reject, at its sole discretion, from the Platform any electronic communications or content deemed not to be in compliance with the corporate policies and procedures of Allrounder Baby. We may be required to share Your personal information with government authorities and agencies for the purposes of verification of identity or for prevention, detection or investigation, including of cyber incidents, prosecution and punishment of offences. You agree and consent for Allrounder Baby to disclose Your information, if so required, under applicable law.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>17. Termination</Text>

              <Text style={styles.leadText}>
                In the event it is determined by Us that You have violated any of these Terms of Use, We shall have the right, at Our sole discretion, to suspend Your use of and prohibit access to any or all features/parts of the Platform forthwith. Any such suspension or termination of access to Platform may be effected by Us without providing You with a prior written notice in this regard. Upon such termination of access to the Platform, these Terms of Use, as applicable to You, will be deemed to have been terminated and no refund of any payments made by You shall be required to be made by Allrounder Baby.
              </Text>
              <Text style={styles.leadText}>
                You acknowledge and agree that, upon termination, You shall immediately destroy any copies made of any portion of the content contained on the Platform other than User Data. You acknowledge and agree that Allrounder Baby shall not be liable to You or any third party claiming through You, for any suspension or termination of access to Platform.
              </Text>
              <Text style={styles.leadText}>
                These Terms of Use shall stand terminated upon Your closing of Your account on the Platform.
              </Text>
              <Text style={styles.leadText}>
                The rights and obligations of the parties under this Terms of Use, which either expressly or by their nature survive the termination of these Terms of Use including but not limited to Paragraph 8 (Intellectual Property), Paragraph 12 (Privacy and Confidentiality), Paragraph 19 (Indemnity), Paragraph 21 (Governing Law and Dispute Resolution), Paragraph 24 (Notice) and Sub-Paragraph 2 of Paragraph 17 shall survive the termination of this Agreement.
              </Text>
              <Text style={styles.leadText}>
                Except as otherwise specifically provided herein, the termination of these Terms of Use for any reason whatsoever shall be without prejudice to any rights or obligations accrued to or in respect of the parties prior to the date of termination.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>18. Disclaimer of Warranties and Limitation of Liability</Text>

              <Text style={styles.leadText}>
                Allrounder Baby does not endorse or act on behalf of any third party. In the event You engage the services of / interact with any third party, through the Platform, Allrounder Baby will not be liable to You for any act or omission by such third party in relation thereto.
              </Text>
              <Text style={styles.leadText}>
                While our Services have been assessed by professionals and have been designed to expand the potential of children, there is no express guarantee that this will work for every child to the same degree. We hereby expressly disclaim all warranties and representations of any kind with respect to any and all content and features available on the Platform, including but not limited to
              </Text>
              <View style={[styles.infoBox, isLandscape ? infoBoxLandscape : null]}>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    1. warranties as to merchantability or use for a particular purpose whether or not Allrounder Baby knows or has reason to know or has been advised of any such purpose or
                  </Text>
                </Text>
                <Text style={styles.bulletPoint}>
                  <Text style={styles.bulletText}>
                    2. warranties as to any results to be obtained from any use of Allrounder Baby content or information derived from use of the Platform.
                  </Text>
                </Text>
              </View>
              <Text style={styles.leadText}>
                Allrounder Baby shall have no liability for any losses, direct or indirect, in contract, tort, or otherwise, incurred in connection with the Allrounder Baby content on the Platform, including but not limited to commercial or economic loss or for any decision made or action taken by any party in reliance upon the Allrounder Baby content.
              </Text>
              <Text style={styles.leadText}>
                You acknowledge that We are not responsible for any exercises that are carried out to help Your child build on concepts they learn in the course of the Services. You should exercise caution and take due care of Your surroundings, Your capabilities and Your child’s capabilities while carrying out such exercises or activities and the safety of Your child and Yourself is Your responsibility. We are not liable for any disputes, claims, losses, injuries, or damage of any kind in relation to Your use of the Services including any that might arise out of or relate to:
              </Text>
              <View style={styles.appText}>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    1. Your use of the Services provided by Us; and/or
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    2. caused by events beyond Our control.
                  </Text>
                </View>
              </View>
              <Text style={[
                styles.leadText,
                {
                  backgroundColor: isDarkMode ? '#282c34' : '#ffffff',
                  marginTop: 20,
                },
              ]}>
                The Platform, all the materials and services, included on or otherwise made available to You through this Platform is provided by Allrounder Baby on an "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing Paragraph, Allrounder Baby does not warrant that:
              </Text>

              <View style={[
                styles.sectionContainer,
                isLandscape ? landscapeSection : null,
                { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
                { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
              ]}>
                <View style={styles.containerss}>
                  <Text style={styles.bodyText}>
                    ⚠️ The Platform will be constantly available, or available at all;
                  </Text>
                  <Text style={styles.bodyText}>
                    ⚠️ The information on the Platform or provided through the Website is complete, true, accurate or not misleading; or
                  </Text>
                  <Text style={styles.bodyText}>
                    ⚠️ The quality of and results from the use of any products, services, information, or other material that You obtain through the Platform will meet Your expectations.
                  </Text>
                </View>
              </View>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>19. Indemnity</Text>
              <View style={styles.appText}>
                <Text style={[
                  styles.platformtext,
                  {
                    color: isDarkMode ? '#000 ' : '#00796B',
                    marginLeft: 20,
                    marginBottom: 0,
                  }
                ]}>
                  You agree to indemnify and hold  Allrounder Baby harmless from:</Text>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    1. any actions, claims, demands, suits, damages, losses, penalties, interest and other charges and expenses (including legal fees and other dispute resolution costs) made by any Person due to or arising out of Your use of the Platform, any violation of the terms of these Terms of Use or any other agreement executed with Allrounder Baby or another person by You;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    2. any acts or deeds, including for any non-compliance or violation, of any applicable law, rules, regulations on Your part;
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    3. for fraud committed by You; or
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    4. Your infringement of any intellectual property or other right of any person or entity; or
                  </Text>
                </View>
                <View style={styles.listItem}>
                  <Text style={styles.leadText}>
                    5. as a result of any threatening, libelous, obscene, harassing or offensive material posted transmitted by You on the Platform. Users outside India must comply with their local regulations regarding online education and payment processing. If a country’s laws restrict digital course transactions, the user is responsible for ensuring compliance before purchasing.
                  </Text>
                </View>
              </View>
              <Text style={[
                styles.leadText,
                {
                  marginTop: 20,
                }
              ]}>
                Your obligations under this Paragraph 19 shall survive the termination of these Terms of Use in accordance with Paragraph 17 above.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>20. Foreign Jurisdictions</Text>

              <Text style={styles.leadText}>
                You are expressly notified that many states and foreign countries all have their own regulations that must be observed in relation to Your use or access of the Platform. You must make Your own assessment regarding, and are responsible for compliance with, regulatory requirements as may be applicable to Your use and access of the Platform in such jurisdictions.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>21. Governing Law and Dispute Resolution</Text>
              <Text style={styles.leadText}>
                These Terms of Use shall be governed by and construed in accordance with the laws of the Republic of India and subject to the provisions of arbitration set out herein, the courts at Kolkata, India shall have exclusive jurisdiction in relation to any Disputes (defined below) arising out of or in connection with these Terms of Use subject to the provisions of this Paragraph 21, without regard to any conflict of laws.
              </Text>
              <Text style={styles.leadText}>
                Any action, dispute or difference arising under or relating to this Terms of Use (Dispute) shall at the first instance be resolved through good faith negotiations between the parties hereto, which negotiations shall begin promptly, within 15 (fifteen) days after a party has delivered to the other party a written request for such consultation. If the parties are unable to resolve the Dispute in question within 15 (fifteen) days of the commencement of negotiations, such Dispute shall be referred to and finally resolved by arbitration in accordance with the Arbitration and Conciliation Act, 1996, as amended from time to time and rules prescribed thereunder. When any Dispute is under arbitration, except for the matters under dispute, Allrounder Baby and You shall continue to exercise the remaining respective rights and fulfil the remaining respective obligations under this Terms of Use.
              </Text>
              <Text style={styles.leadText}>
                The arbitration shall be conducted by a sole arbitrator jointly appointed by Allrounder Baby and You. If parties fail to appoint an arbitrator within 30 (thirty) days after service of the notice of arbitration, such arbitrator shall be appointed in accordance with provisions of the Arbitration and Conciliation Act, 1996.The venue of arbitration shall be Kolkata, India.
              </Text>
              <Text style={styles.leadText}>
                The language of the arbitration proceedings and of all written decisions and correspondence relating to the arbitration shall be English.
              </Text>
              <Text style={styles.leadText}>
                You agree and acknowledge that the provisions of Paragraph 8 (Intellectual Property) and Paragraph 12 (Privacy and Confidentiality) are of importance to Allrounder Baby and monetary compensation may not constitute adequate relief and remedy to Allrounder Baby for non-performance by You of Your obligations thereunder. Accordingly, Allrounder Baby shall be entitled to claim specific performance and seek mandatory and/or perpetual injunctions requiring You to perform Your duties and obligations under such provisions.
              </Text>
            </View>
            <View>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>22. Severability</Text>
              <Text style={styles.leadText}>
                If any term, provision, covenant or restriction of these Terms of Use is held by a court of competent jurisdiction to be invalid, void or unenforceable, the remainder of the terms, provisions, covenants and restrictions of these Terms of Use shall remain in full force and effect and shall in no way be affected, impaired or invalidated.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>23. No Waiver</Text>
              <Text style={styles.leadText}>
                The rights and remedies available under this Terms of Use may be exercised as often as necessary and are cumulative and not exclusive of rights or remedies provided by law. It may be waived only in writing. Delay in exercising or non-exercise of any such right or remedy does not constitute a waiver of that right or remedy, or any other right or remedy.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>24. General</Text>
              <Text style={styles.leadText}>
                These Terms of Use comprise the full and complete agreement between You and Allrounder Baby with respect to the use of
                the Platform and supersedes and cancels all prior communications, understandings and agreements between You and
                Allrounder Baby, whether written or oral, expressed or implied with respect thereto.
              </Text>
              <Text style={styles.leadText}>
                Allrounder Baby shall be entitled to assign their rights and obligations hereunder to any Affiliate, third party or as part of any restructuring, business combination, merger or acquisition.
              </Text>
              <Text style={styles.leadText}>
                Any notice to be given in connection with these Terms of Use shall be delivered via email to Allrounder Baby at support@allrounderbaby.com or to You at the email address provided by You in Your profile. You consent to the use of electronic communications in order to the electronic delivery of notices in relation to any matter under these Terms of Use.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>25. Cashback for Feedback</Text>

              <Text style={styles.leadText}>
                Allrounder Baby values customer insights and strives to enhance its programs based on real-world user experiences. To encourage meaningful feedback, the Company provides cashback incentives to eligible users who submit comprehensive feedback. Users must have completed at least one full course on the platform to qualify, and the feedback must be detailed, genuine, and constructive, covering aspects such as content quality, usability, and observed impact on child development. The Company reserves the right to specify the format of the feedback, which may include written testimonials, audio recordings, or video submissions. The feedback may be used for promotional and research purposes, and by participating in the cashback program, the user consents to such use. Cashback is granted only once per user per course, and multiple claims for the same course will not be accepted.
              </Text>
              <Text style={styles.leadText}>
                Eligible users will receive a cashback percentage of their original purchase price, the percentage and maximum cashback limit being determined at the sole discretion of the Company. Cashback will be processed within 60 days from the date of approval and will be credited to the original payment method, such as bank transfer or digital payment wallets. If the payment was made in USD or EUR, the cashback will be converted at the prevailing exchange rate at the time of processing, and any applicable foreign exchange conversion fees will be deducted. The Company will process cashback only to the bank account registered in the user's name, whether domestic or international. In case of an international payout, the user must provide complete bank details, including IBAN or SWIFT code, and ensure that their financial institution can receive international transactions. Any intermediary bank fees or deductions levied by international banking systems shall be borne by the user, and the Company will not be responsible for variations in final credited amounts due to currency fluctuations or banking charges.
              </Text>
              <Text style={styles.leadText}>
                Users are solely responsible for ensuring that their bank account details are accurate and up to date. Any changes in bank account details must be updated through the user profile or by submitting a request to support@allrounderbaby.com, along with necessary verification documents. Failure to provide accurate details may lead to delays or rejection of cashback payments, and the Company shall not be liable for payments sent to incorrect or outdated accounts due to user negligence. For users based in India, providing a valid PAN number is mandatory for cashback processing in compliance with applicable tax regulations. International users may be required to submit equivalent tax identification or banking compliance documents as per their country’s regulatory requirements. If KYC verification is required, the user must provide a valid government-issued identity proof and address verification before the cashback can be processed.
              </Text>
              <Text style={styles.leadText}>
                Cashback incentives will not be applicable to users who have already availed a refund for the purchased course. If the feedback is found to be incomplete, misleading, inaccurate, biased, or copied from other sources, the Company reserves the right to reject the cashback request. Any user found to be abusing the cashback system by submitting fabricated testimonials, using AI-generated content, or engaging in fraudulent activities may be permanently disqualified from all future cashback programs. The Company reserves the right to modify, suspend, or terminate the cashback program at any time without prior notice, and any modifications will take effect immediately upon publication. If any fraudulent activity is suspected, the Company reserves the right to withhold cashback at its sole discretion.
              </Text>
            </View>
            <View style={[
              styles.sectionContainer,
              { backgroundColor: isDarkMode ? '#282c34' : '#ffffff' },
              { borderColor: isDarkMode ? '#444' : '#e0e0e0' }
            ]}>
              <Text style={[
                styles.sectionHeader,
                { color: isDarkMode ? '#fff' : '#1434a4' }
              ]}>26 Refer & Earn</Text>
              <Text style={styles.leadText}>
                Allrounder Baby offers a referral program where existing users can earn monetary rewards by referring new customers to purchase courses or services. The Referrer must be a registered and active user with an account in good standing, and the Referred User must be a first-time customer who has never previously signed up or made a purchase on the platform. To qualify for the referral bonus, the Referred User must use the unique referral code or link provided by the Referrer at the time of registration and checkout and must complete the payment process successfully. The referral bonus will be calculated based on the final amount paid by the Referred User, excluding any discounts, refunds, or promotional offers applied to the purchase.
              </Text>
              <Text style={styles.leadText}>
                Referral earnings will be credited within 60 days after the referred user's successful and verified payment. The payout will be processed in the same currency as the original transaction, which may be INR, USD, or EUR. If the referral payment involves an international transaction, the payout will be converted at the best available foreign exchange rate at the time of processing. Any banking fees, forex conversion charges, or intermediary bank deductions applicable to international transactions will be borne by the Referrer. The minimum payout threshold may apply, and multiple referral earnings may be combined into a single payout if they do not individually meet the threshold. The Referrer must ensure that their bank account details, including SWIFT or IBAN codes for international transfers, are accurately provided and updated. The Company shall not be responsible for payments sent to incorrect or outdated accounts due to user negligence.
              </Text>
              <Text style={styles.leadText}>
                To ensure compliance with financial and regulatory laws, all Referrers must complete KYC verification before withdrawal of referral earnings. For Indian users, submission of a valid PAN number is mandatory if the referral earnings exceed government-mandated tax thresholds. International users may be required to provide their tax identification number or other necessary documentation based on the regulatory requirements of their respective countries. Referral earnings will only be credited to a bank account registered in the user’s name, and no third-party accounts will be permitted. Users must ensure that their payment details remain accurate and up to date to avoid processing delays or payment rejections.
              </Text>
              <Text style={styles.leadText}>
                Fraud prevention measures have been implemented to maintain the integrity of the referral program. Self-referrals, duplicate accounts, fake sign-ups, and the use of bots or temporary email addresses to generate referrals are strictly prohibited. Any Referrer found engaging in fraudulent activities or misrepresenting the referral program may face account suspension, forfeiture of earnings, or legal action. If a referral is found to be invalid, manipulated, or artificial, the payout will be withheld or revoked at the Company's discretion.
              </Text>
              <Text style={styles.leadText}>
                The Company reserves the right to modify, suspend, or terminate the referral program at any time without prior notice. If the program is discontinued, any pending referral payouts may be canceled, and users will not be entitled to compensation. The Company reserves the sole discretion to resolve any disputes related to referral eligibility, payout amounts, or suspected fraud. Users participating in the referral program acknowledge and accept the Company's right to amend the terms of the program as necessary to comply with financial regulations, prevent misuse, and ensure fairness.
              </Text>
            </View>

          </View>
        </ScreenScroll>
      </View>
    </>
  );
};

const styles = StyleSheet.create({
  appText: {
    backgroundColor: '#E0F7FA',
    borderRadius: 10,
    padding: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 10,
    marginTop: 10,
    alignItems: 'flex-start',
  },
  infoBox: {
    backgroundColor: '#E0F7FA',
    borderRadius: 15,
    padding: 10,
    marginHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 8,
    width: '95%',
    maxWidth: 600,
    marginBottom: 10,
  },
  platformtext: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00796B',
    marginBottom: 15,
    paddingHorizontal: 0,
    textAlign: 'left',
  },
  bulletPoint: {
    flexDirection: 'row',
    marginBottom: 10,
    paddingLeft: 5,
  },
  bulletText: {
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 15,
    color: '#666',
    paddingHorizontal: 15,
    textAlign: 'justify',
  },
  container: { flex: 1, backgroundColor: '#f1f2f2' },
  containerss: {
    borderWidth: 2,
    borderColor: '#E60000',
    borderRadius: 5,
    padding: 15,
    margin: 10,
    backgroundColor: '#FFFFFF',
  },
  bodyText: {
    fontSize: 14,
    color: '#333333',
    lineHeight: 22,
    marginBottom: 10,
    textAlign: 'justify',
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    marginTop: 20,
    color: '#1434a4',
    paddingHorizontal: 20,
    textAlign: 'center',
  },
  leadText: {
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 15,
    color: '#666',
    paddingHorizontal: 20,
    textAlign: 'justify',
  },
  sectionHeader: {
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 0,
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 20,
  },
});

export default TermsofService;
